### ISSUE TITLE
NPM Update

### ISSUE THREAD

**Issue by claytonbwell** [joshukraine/middleman-gulp#17]
Ran bin/setup and got a notification to update 5.6.0 -> 6.4.0 (Run npm i -g npm to update). I don't want to run the update if it's not compatible. Any advice?

**Comment by joshukraine** [comment]
That shouldn't have any effect on middleman-gulp. As long as your installed version of Node.js is 6.x or higher, you'll be just fine. For example, I currently have node 8.11.3 installed and I'm running npm 6.1.0.
